name: ums-stack
services:
  mysql:
    container_name: ums-mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpasword11
      MYSQL_DATABASE: webappdb
    ports:
      - "3306:3306"
    volumes:
      - mydb:/var/lib/mysql

volumes:
  mydb:
    name: ums-mysqldb-data-v1 #Explicitely name the volume
    driver: local # optional, as local is default driver
    labels:     # Adds metadata to the volume using labels
      project: "ums-stack" #Label to indicate the project name
      component: "mysql-database" #Label to specify that this volume is for the MYSQL database
      purpose: "persistent-storage" #Label to indicate the purpose of this volume
